-- ============================================================================
-- Complete PostgreSQL schema for search-by-image application
-- ============================================================================

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- TIER 0: Tables with no foreign keys
-- ============================================================================

CREATE TABLE platforms (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    full_name       VARCHAR(100),
    phone           VARCHAR(20),
    country         VARCHAR(50),
    city            VARCHAR(50),
    state           VARCHAR(50),
    zip             VARCHAR(10),
    street_address  VARCHAR(255),
    profile_image   VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ
);

CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_email    ON users (email);

CREATE TABLE flash_sales (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    start_time  TIMESTAMP    NOT NULL,
    end_time    TIMESTAMP    NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_by  BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_flash_sales_status     ON flash_sales (status);
CREATE INDEX idx_flash_sales_start_time ON flash_sales (start_time);
CREATE INDEX idx_flash_sales_end_time   ON flash_sales (end_time);

-- ============================================================================
-- TIER 1: Depend on platforms and/or users
-- ============================================================================

CREATE TABLE categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id     BIGINT       NOT NULL REFERENCES platforms(id),
    category_id     VARCHAR(100) NOT NULL,
    category_name   VARCHAR(255),
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ,
    UNIQUE (platform_id, category_id)
);

CREATE INDEX idx_categories_platform    ON categories (platform_id);
CREATE INDEX idx_categories_category_id ON categories (category_id);
CREATE INDEX idx_categories_name        ON categories (category_name);

CREATE TABLE shops (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id     BIGINT       NOT NULL REFERENCES platforms(id),
    shop_name       VARCHAR(255),
    shop_link       TEXT,
    shop_rating     NUMERIC(3,2),
    shop_location   VARCHAR(255),
    shop_age        VARCHAR(100),
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ,
    UNIQUE (platform_id, shop_name)
);

CREATE INDEX idx_shops_platform ON shops (platform_id);
CREATE INDEX idx_shops_name     ON shops (shop_name);

CREATE TABLE addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users(id),
    street_address  VARCHAR(255) NOT NULL,
    email           VARCHAR(100),
    phone           VARCHAR(20),
    city            VARCHAR(50),
    state           VARCHAR(50),
    zip             VARCHAR(10),
    country         VARCHAR(50),
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ
);

CREATE INDEX idx_addresses_user_id ON addresses (user_id);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(36)  NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL REFERENCES users(id),
    expiry_date TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_refresh_tokens_token   ON refresh_tokens (token);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(36)  NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL REFERENCES users(id),
    expiry_date TIMESTAMPTZ  NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_password_reset_token ON password_reset_tokens (token);

-- ============================================================================
-- TIER 2: Depend on shops and/or categories
-- ============================================================================

CREATE TABLE shop_badges (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT       NOT NULL REFERENCES shops(id),
    badge   VARCHAR(100) NOT NULL,
    UNIQUE (shop_id, badge)
);

CREATE INDEX idx_shop_badges_shop ON shop_badges (shop_id);

CREATE TABLE seller_info (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id                 BIGINT       NOT NULL UNIQUE REFERENCES shops(id),
    positive_feedback_rate  INTEGER,
    has_vip                 BOOLEAN      DEFAULT FALSE,
    avg_delivery_time       VARCHAR(100),
    avg_refund_time         VARCHAR(100)
);

CREATE INDEX idx_seller_info_shop ON seller_info (shop_id);

CREATE TABLE products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id             VARCHAR(100) NOT NULL UNIQUE,
    platform_id         BIGINT       NOT NULL REFERENCES platforms(id),
    shop_id             BIGINT       REFERENCES shops(id),
    category_fk         BIGINT       REFERENCES categories(id),
    title               VARCHAR(500) NOT NULL,
    price               VARCHAR(50),
    image               TEXT,
    link                TEXT         NOT NULL,
    sales_count         VARCHAR(50),
    location            VARCHAR(255),
    details_scraped     BOOLEAN      DEFAULT FALSE,
    details_scraped_at  TIMESTAMPTZ,
    extraction_quality  INTEGER,
    extracted_at        TIMESTAMPTZ,
    migration_version   INTEGER      DEFAULT 2,
    created_at          TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ
);

CREATE INDEX idx_products_item_id          ON products (item_id);
CREATE INDEX idx_products_platform         ON products (platform_id);
CREATE INDEX idx_products_shop             ON products (shop_id);
CREATE INDEX idx_products_category         ON products (category_fk);
CREATE INDEX idx_products_details_scraped  ON products (details_scraped);

CREATE TABLE scraping_jobs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            VARCHAR(100) NOT NULL UNIQUE,
    platform_id       BIGINT       REFERENCES platforms(id),
    category_fk       BIGINT       REFERENCES categories(id),
    search_type       VARCHAR(20),
    status            VARCHAR(20)  NOT NULL,
    keyword           VARCHAR(500),
    category_id       VARCHAR(100),
    category_name     VARCHAR(255),
    max_products      INTEGER,
    max_pages         INTEGER,
    current_page      INTEGER      DEFAULT 0,
    products_scraped  INTEGER      DEFAULT 0,
    details_scraped   INTEGER      DEFAULT 0,
    details_failed    INTEGER      DEFAULT 0,
    total_products    INTEGER      DEFAULT 0,
    updated_products  INTEGER      DEFAULT 0,
    error_message     TEXT,
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ
);

CREATE INDEX idx_jobs_status      ON scraping_jobs (status);
CREATE INDEX idx_jobs_created_at  ON scraping_jobs (created_at);
CREATE INDEX idx_jobs_category_fk ON scraping_jobs (category_fk);
CREATE INDEX idx_jobs_category_id ON scraping_jobs (category_id);

-- ============================================================================
-- TIER 3: Depend on products
-- ============================================================================

CREATE TABLE product_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT       NOT NULL UNIQUE REFERENCES products(id),
    full_title          VARCHAR(1000),
    full_description    TEXT,
    brand               VARCHAR(255),
    rating              VARCHAR(20),
    review_count        VARCHAR(50),
    sales_volume        VARCHAR(50),
    original_price      VARCHAR(50),
    in_stock            BOOLEAN,
    shipping_info       TEXT,
    dq_has_title        BOOLEAN,
    dq_has_price        BOOLEAN,
    dq_has_images       BOOLEAN,
    dq_has_variants     BOOLEAN,
    dq_has_specs        BOOLEAN,
    dq_has_brand        BOOLEAN,
    dq_has_reviews      BOOLEAN,
    dq_has_description  BOOLEAN,
    dq_has_sales_volume BOOLEAN,
    dq_has_shop_name    BOOLEAN,
    dq_completeness     INTEGER
);

CREATE TABLE product_embeddings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT       NOT NULL UNIQUE REFERENCES products(id) ON DELETE CASCADE,
    embedding        vector(512)  NOT NULL,
    source_image_url TEXT,
    model_version    VARCHAR(50)  DEFAULT 'clip-vit-base-patch32',
    created_at       TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_product_embeddings_product ON product_embeddings (product_id);
CREATE INDEX idx_product_embeddings_vector
    ON product_embeddings
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

CREATE TABLE product_guarantees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES products(id),
    guarantee   VARCHAR(500) NOT NULL
);

CREATE INDEX idx_guarantees_product ON product_guarantees (product_id);

CREATE TABLE product_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES products(id),
    url         TEXT         NOT NULL,
    source_type VARCHAR(20)  DEFAULT 'gallery',
    sort_order  INTEGER      DEFAULT 0
);

CREATE INDEX idx_product_images_product ON product_images (product_id);

CREATE TABLE product_search_meta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT       NOT NULL UNIQUE REFERENCES products(id),
    category_fk     BIGINT       REFERENCES categories(id),
    search_keyword  VARCHAR(500),
    category_id     VARCHAR(100),
    category_name   VARCHAR(255),
    page_number     INTEGER
);

CREATE INDEX idx_search_meta_keyword     ON product_search_meta (search_keyword);
CREATE INDEX idx_search_meta_category    ON product_search_meta (category_name);
CREATE INDEX idx_search_meta_category_id ON product_search_meta (category_id);
CREATE INDEX idx_search_meta_category_fk ON product_search_meta (category_fk);

CREATE TABLE product_specs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES products(id),
    spec_key    VARCHAR(255) NOT NULL,
    spec_value  TEXT
);

CREATE INDEX idx_specs_product ON product_specs (product_id);

CREATE TABLE product_variants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT       NOT NULL REFERENCES products(id),
    variant_type VARCHAR(255) NOT NULL
);

CREATE INDEX idx_variants_product ON product_variants (product_id);

CREATE TABLE orders (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       BIGINT         NOT NULL REFERENCES users(id),
    shop_id           BIGINT         REFERENCES shops(id),
    total_amount      NUMERIC(19,4)  NOT NULL DEFAULT 0,
    status            VARCHAR(30)    NOT NULL,
    payment_status    VARCHAR(20)    NOT NULL,
    payment_method    VARCHAR(50),
    transaction_id    VARCHAR(100),
    shipping_address  TEXT,
    note              TEXT,
    confirmed_at      TIMESTAMP,
    created_at        TIMESTAMP      NOT NULL
);

CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_shop     ON orders (shop_id);
CREATE INDEX idx_orders_status   ON orders (status);

CREATE TABLE flash_sale_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flash_sale_id       BIGINT        NOT NULL REFERENCES flash_sales(id),
    product_id          BIGINT        NOT NULL REFERENCES products(id),
    sale_price          NUMERIC(19,4) NOT NULL,
    original_price      NUMERIC(19,4) NOT NULL,
    flash_stock_limit   INTEGER       NOT NULL,
    sold_count          INTEGER       NOT NULL DEFAULT 0,
    limit_per_customer  INTEGER       NOT NULL DEFAULT 1,
    version             BIGINT
);

CREATE INDEX idx_flash_sale_items_sale    ON flash_sale_items (flash_sale_id);
CREATE INDEX idx_flash_sale_items_product ON flash_sale_items (product_id);

CREATE TABLE pre_orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id             BIGINT        NOT NULL REFERENCES users(id),
    product_id              BIGINT        NOT NULL REFERENCES products(id),
    quantity                INTEGER       NOT NULL,
    unit_price              NUMERIC(19,4) NOT NULL,
    deposit_amount          NUMERIC(19,4),
    expected_release_date   DATE,
    status                  VARCHAR(30)   NOT NULL,
    version                 BIGINT        NOT NULL DEFAULT 0,
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP
);

CREATE INDEX idx_pre_orders_customer ON pre_orders (customer_id);
CREATE INDEX idx_pre_orders_product  ON pre_orders (product_id);
CREATE INDEX idx_pre_orders_status   ON pre_orders (status);

-- ============================================================================
-- TIER 4: Depend on variants / orders
-- ============================================================================

CREATE TABLE variant_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id  BIGINT       NOT NULL REFERENCES product_variants(id),
    value       VARCHAR(500) NOT NULL,
    image_url   TEXT,
    vid         VARCHAR(100)
);

CREATE INDEX idx_variant_options_variant ON variant_options (variant_id);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT        NOT NULL REFERENCES orders(id),
    product_id  BIGINT        NOT NULL REFERENCES products(id),
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(19,4) NOT NULL,
    subtotal    NUMERIC(19,4) NOT NULL
);

CREATE INDEX idx_order_items_order   ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

CREATE TABLE order_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL REFERENCES orders(id),
    from_status VARCHAR(30),
    to_status   VARCHAR(30)  NOT NULL,
    changed_by  VARCHAR(100),
    note        VARCHAR(500),
    changed_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_order_status_history_order      ON order_status_history (order_id);
CREATE INDEX idx_order_status_history_changed_at ON order_status_history (changed_at);
